name: BestiumExample
version: '${version}'
main: cz.jeme.bestiumexample.BestiumExample
bootstrapper: cz.jeme.bestiumexample.BestiumExampleBootstrapper
api-version: '1.21.11'
author: Hužva
description: Example plugin showcasing features of Bestium

# Depend on Bestium
dependencies:
  bootstrap:
    Bestium:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    Bestium:
      join-classpath: true
      
permissions: 
  bestium_example.command.bexample:
    default: op