name: BestiumExample
version: '${version}'
main: cz.jeme.bestiumexample.BestiumExample
bootstrapper: cz.jeme.bestiumexample.BestiumExampleBootstrapper
api-version: '1.21.4'
author: Hužva
description: Example plugin showcasing features of Bestium
dependencies:
  bootstrap:
    Bestium:
      load: BEFORE
      required: true
      join-classpath: true